import type { AdminDashboard } from "./types";

export const mockDashboardData: AdminDashboard = {
  kpis: {
    total_egresados: 1247,
    total_empresas: 89,
    ofertas_activas: 156,
    tasa_empleabilidad: 72.5,
  },
  distribucionEgresados: [
    { carrera_id: "1", carrera: "Ingeniería de Sistemas", facultad: "Ingeniería", total_egresados: 342, egresados_empleados: 285, tasa_empleabilidad: 83.3 },
    { carrera_id: "2", carrera: "Ingeniería Industrial", facultad: "Ingeniería", total_egresados: 218, egresados_empleados: 168, tasa_empleabilidad: 77.1 },
    { carrera_id: "3", carrera: "Administración de Empresas", facultad: "Ciencias Económicas", total_egresados: 195, egresados_empleados: 142, tasa_empleabilidad: 72.8 },
    { carrera_id: "4", carrera: "Contaduría Pública", facultad: "Ciencias Económicas", total_egresados: 156, egresados_empleados: 98, tasa_empleabilidad: 62.8 },
    { carrera_id: "5", carrera: "Derecho", facultad: "Ciencias Jurídicas", total_egresados: 134, egresados_empleados: 87, tasa_empleabilidad: 64.9 },
    { carrera_id: "6", carrera: "Comunicación Social", facultad: "Humanidades", total_egresados: 98, egresados_empleados: 61, tasa_empleabilidad: 62.2 },
    { carrera_id: "7", carrera: "Psicología", facultad: "Ciencias Sociales", total_egresados: 104, egresados_empleados: 72, tasa_empleabilidad: 69.2 },
  ],
  demandaHabilidades: [
    { habilidad_id: "1", habilidad: "JavaScript/TypeScript", tipo: "TECNICA", categoria: "Desarrollo", total_ofertas: 89, ofertas_obligatoria: 72, ofertas_deseable: 17 },
    { habilidad_id: "2", habilidad: "Python", tipo: "TECNICA", categoria: "Desarrollo", total_ofertas: 76, ofertas_obligatoria: 58, ofertas_deseable: 18 },
    { habilidad_id: "3", habilidad: "SQL/Base de Datos", tipo: "TECNICA", categoria: "Datos", total_ofertas: 68, ofertas_obligatoria: 54, ofertas_deseable: 14 },
    { habilidad_id: "4", habilidad: "Trabajo en Equipo", tipo: "Blanda", categoria: null, total_ofertas: 92, ofertas_obligatoria: 45, ofertas_deseable: 47 },
    { habilidad_id: "5", habilidad: "Comunicación Efectiva", tipo: "Blanda", categoria: null, total_ofertas: 85, ofertas_obligatoria: 38, ofertas_deseable: 47 },
    { habilidad_id: "6", habilidad: "React/Next.js", tipo: "TECNICA", categoria: "Desarrollo", total_ofertas: 64, ofertas_obligatoria: 51, ofertas_deseable: 13 },
    { habilidad_id: "7", habilidad: "AWS/Cloud", tipo: "TECNICA", categoria: "Infraestructura", total_ofertas: 52, ofertas_obligatoria: 41, ofertas_deseable: 11 },
    { habilidad_id: "8", habilidad: "Gestión de Proyectos", tipo: "Blanda", categoria: null, total_ofertas: 58, ofertas_obligatoria: 29, ofertas_deseable: 29 },
    { habilidad_id: "9", habilidad: "Docker/Kubernetes", tipo: "TECNICA", categoria: "Infraestructura", total_ofertas: 45, ofertas_obligatoria: 36, ofertas_deseable: 9 },
    { habilidad_id: "10", habilidad: "Machine Learning", tipo: "TECNICA", categoria: "Datos", total_ofertas: 38, ofertas_obligatoria: 28, ofertas_deseable: 10 },
  ],
  ofertasPorMes: [
    { mes: new Date("2025-07-01"), total_ofertas: 23, empresas_unicas: 18 },
    { mes: new Date("2025-08-01"), total_ofertas: 31, empresas_unicas: 24 },
    { mes: new Date("2025-09-01"), total_ofertas: 28, empresas_unicas: 21 },
    { mes: new Date("2025-10-01"), total_ofertas: 42, empresas_unicas: 32 },
    { mes: new Date("2025-11-01"), total_ofertas: 38, empresas_unicas: 28 },
    { mes: new Date("2025-12-01"), total_ofertas: 19, empresas_unicas: 15 },
    { mes: new Date("2026-01-01"), total_ofertas: 35, empresas_unicas: 27 },
    { mes: new Date("2026-02-01"), total_ofertas: 48, empresas_unicas: 36 },
    { mes: new Date("2026-03-01"), total_ofertas: 52, empresas_unicas: 39 },
    { mes: new Date("2026-04-01"), total_ofertas: 41, empresas_unicas: 31 },
  ],
  postulacionesPorMes: [
    { mes: new Date("2025-07-01"), total_postulaciones: 156, ofertas_postuladas: 89, egresados_unicos: 134 },
    { mes: new Date("2025-08-01"), total_postulaciones: 203, ofertas_postuladas: 112, egresados_unicos: 178 },
    { mes: new Date("2025-09-01"), total_postulaciones: 189, ofertas_postuladas: 98, egresados_unicos: 156 },
    { mes: new Date("2025-10-01"), total_postulaciones: 267, ofertas_postuladas: 145, egresados_unicos: 223 },
    { mes: new Date("2025-11-01"), total_postulaciones: 234, ofertas_postuladas: 128, egresados_unicos: 198 },
    { mes: new Date("2025-12-01"), total_postulaciones: 142, ofertas_postuladas: 76, egresados_unicos: 119 },
    { mes: new Date("2026-01-01"), total_postulaciones: 218, ofertas_postuladas: 118, egresados_unicos: 187 },
    { mes: new Date("2026-02-01"), total_postulaciones: 312, ofertas_postuladas: 167, egresados_unicos: 265 },
    { mes: new Date("2026-03-01"), total_postulaciones: 356, ofertas_postuladas: 189, egresados_unicos: 298 },
    { mes: new Date("2026-04-01"), total_postulaciones: 289, ofertas_postuladas: 156, egresados_unicos: 241 },
  ],
  tasaContratacionCohorte: [
    { anio_egreso: 2020, carrera: "Ingeniería de Sistemas", total_egresados: 78, contratados: 71, tasa_contratacion: 91.0 },
    { anio_egreso: 2020, carrera: "Ingeniería Industrial", total_egresados: 52, contratados: 44, tasa_contratacion: 84.6 },
    { anio_egreso: 2021, carrera: "Ingeniería de Sistemas", total_egresados: 85, contratados: 76, tasa_contratacion: 89.4 },
    { anio_egreso: 2021, carrera: "Ingeniería Industrial", total_egresados: 58, contratados: 48, tasa_contratacion: 82.8 },
    { anio_egreso: 2022, carrera: "Ingeniería de Sistemas", total_egresados: 92, contratados: 79, tasa_contratacion: 85.9 },
    { anio_egreso: 2022, carrera: "Administración de Empresas", total_egresados: 67, contratados: 52, tasa_contratacion: 77.6 },
    { anio_egreso: 2023, carrera: "Ingeniería de Sistemas", total_egresados: 87, contratados: 68, tasa_contratacion: 78.2 },
    { anio_egreso: 2023, carrera: "Administración de Empresas", total_egresados: 71, contratados: 51, tasa_contratacion: 71.8 },
    { anio_egreso: 2024, carrera: "Ingeniería de Sistemas", total_egresados: 95, contratados: 62, tasa_contratacion: 65.3 },
    { anio_egreso: 2024, carrera: "Administración de Empresas", total_egresados: 74, contratados: 45, tasa_contratacion: 60.8 },
  ],
  ofertasPorUbicacion: [
    { ciudad: "Bogotá", pais: "Colombia", total_ofertas: 67, empresas_unicas: 42, salario_promedio_min: 2500000, salario_promedio_max: 4500000 },
    { ciudad: "Medellín", pais: "Colombia", total_ofertas: 38, empresas_unicas: 28, salario_promedio_min: 2200000, salario_promedio_max: 4000000 },
    { ciudad: "Cali", pais: "Colombia", total_ofertas: 24, empresas_unicas: 19, salario_promedio_min: 2000000, salario_promedio_max: 3500000 },
    { ciudad: "Barranquilla", pais: "Colombia", total_ofertas: 15, empresas_unicas: 12, salario_promedio_min: 1900000, salario_promedio_max: 3200000 },
    { ciudad: "Remote", pais: "Colombia", total_ofertas: 12, empresas_unicas: 10, salario_promedio_min: 2800000, salario_promedio_max: 5500000 },
  ],
};
